GraphiteBase = "https://graphite.thraxil.org/render/"
CheckInterval = 30

[actions]

  [actions.one]
	Metric = "movingAverage(nonNegativeDerivative(nginx.north.requests),'15min')"
	Threshold = 7.0
	Direction = "above"
	Command = "echo there it is"
	CheckInterval = 10

  [actions.two]
	Metric = "summarize(server.aloha.cpu.load_average.1_minute,'7min','avg')"
	Threshold = 1.0
	Direction = "above"
	Command = "echo aloha load avg is too high"
